config/routes.rb
Rails.application.routes.draw do
  resources :line_items

  resources :carts

  get 'store/index'

  resources :products

  root :to => 'store#index', :as => 'store'

end

app/models/cart.rb
class Cart < ActiveRecord::Base
  has_many :line_items, :dependent => :destroy

  def add_product(product_id)
    current_item = line_items.find_by_product_id(product_id)
    if current_item
      current_item.quantity += 1
    else
      current_item = line_items.build(:product_id => product_id)
    end
    current_item
  end


  def total_price
    line_items.to_a.sum { |item| item.total_price }
  end
end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
  belongs_to :product
  belongs_to :cart

  def total_price
    product.price * quantity
  end

end

app/models/product.rb
class Product < ActiveRecord::Base
  default_scope { order('title') }
  has_many :line_items
  before_destroy :ensure_not_referenced_by_any_line_item

  validates :title, :description, :image_url, :presence => true
  validates :price, :numericality => {:greater_than_or_equal_to => 0.01}
  validates :title, :uniqueness => true
  validates :image_url, :format => {
                          :with => %r{\.(gif|jpg|png)\z}i,
                          :message => 'must be a URL for GIF, JPG or PNG image.'
                      }

  private
# ensure that there are no line items referencing this product
  def ensure_not_referenced_by_any_line_item
    if line_items.empty?
      return true
    else
      errors.add(:base, 'Line Items present')
      return false
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :set_share_variable

  protected

  def set_share_variable
    @time = Time.now
  end

  private

  def current_cart
    Cart.find(session[:cart_id])
  rescue ActiveRecord::RecordNotFound
    cart = Cart.create
    session[:cart_id] = cart.id
    cart
  end

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :set_cart, only: [:show, :edit, :update, :destroy]

  # GET /carts
  # GET /carts.json
  def index
    @carts = Cart.all
  end

  # GET /carts/1
  # GET /carts/1.json
  def show
    begin
      @cart = Cart.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      logger.error "Attempt to access invalid cart #{params[:id]}"
      redirect_to store_url, :notice => 'Invalid cart'
    else
      respond_to do |format|
        format.html # show.html.erb
        format.xml { render :xml => @cart }
      end
    end
  end

  # GET /carts/new
  def new
    @cart = Cart.new
  end

  # GET /carts/1/edit
  def edit
  end

  # POST /carts
  # POST /carts.json
  def create
    @cart = Cart.new(cart_params)

    respond_to do |format|
      if @cart.save
        format.html { redirect_to @cart, notice: 'Cart was successfully created.' }
        format.json { render :show, status: :created, location: @cart }
      else
        format.html { render :new }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carts/1
  # PATCH/PUT /carts/1.json
  def update
    respond_to do |format|
      if @cart.update(cart_params)
        format.html { redirect_to @cart, notice: 'Cart was successfully updated.' }
        format.json { render :show, status: :ok, location: @cart }
      else
        format.html { render :edit }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1
  # DELETE /carts/1.json
  def destroy
    @cart = current_cart
    @cart.destroy
    session[:cart_id] = nil
    respond_to do |format|
      format.html { redirect_to(store_url,
                                :notice => 'Your cart is currently empty') }
      format.xml { head :ok }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cart
      #@cart = Cart.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cart_params
      params[:cart]
    end
end

app/controllers/line_items_controller.rb
class LineItemsController < ApplicationController
  before_action :set_line_item, only: [:show, :edit, :update, :destroy]

  # GET /line_items
  # GET /line_items.json
  def index
    @line_items = LineItem.all
  end

  # GET /line_items/1
  # GET /line_items/1.json
  def show
  end

  # GET /line_items/new
  def new
    @line_item = LineItem.new
  end

  # GET /line_items/1/edit
  def edit
  end

  # POST /line_items
  # POST /line_items.json
  def create
    @cart = current_cart
    product = Product.find(params[:product_id])
    @line_item = @cart.add_product(product.id)

    respond_to do |format|
      if @line_item.save
        format.html { redirect_to(@line_item.cart) }
        format.xml { render :xml => @line_item,
                            :status => :created, :location => @line_item }
      else
        format.html { render :action => "new" }
        format.xml { render :xml => @line_item.errors,
                            :status => :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /line_items/1
  # PATCH/PUT /line_items/1.json
  def update
    respond_to do |format|
      if @line_item.update(line_item_params)
        format.html { redirect_to @line_item, notice: 'Line item was successfully updated.' }
        format.json { render :show, status: :ok, location: @line_item }
      else
        format.html { render :edit }
        format.json { render json: @line_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /line_items/1
  # DELETE /line_items/1.json
  def destroy
    @line_item.destroy
    respond_to do |format|
      format.html { redirect_to line_items_url, notice: 'Line item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_line_item
      @line_item = LineItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def line_item_params
      params.require(:line_item).permit(:product_id, :cart_id)
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:title, :description, :image_url, :price)
    end
end

app/controllers/store_controller.rb
class StoreController < ApplicationController
  def index
    @products = Product.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/store_helper.rb
module StoreHelper
end

app/views/carts/_form.html.haml
= form_for @cart do |f|
  - if @cart.errors.any?
    #error_explanation
      %h2= "#{pluralize(@cart.errors.count, "error")} prohibited this cart from being saved:"
      %ul
        - @cart.errors.full_messages.each do |msg|
          %li= msg

  .actions
    = f.submit 'Save'

app/views/carts/edit.html.haml
%h1 Editing cart

= render 'form'

= link_to 'Show', @cart
\|
= link_to 'Back', carts_path

app/views/carts/index.html.haml
%h1 Listing carts

%table
  %thead
    %tr
      %th
      %th
      %th
      
  %tbody
    - @carts.each do |cart|
      %tr
        %td= cart.id
        %td= link_to 'Show', cart
        %td= link_to 'Edit', edit_cart_path(cart)
        %td= link_to 'Destroy', cart, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Cart', new_cart_path

app/views/carts/new.html.haml
%h1 New cart

= render 'form'

= link_to 'Back', carts_path

app/views/carts/show.html.haml
.cart_title Your Cart
%table
  = render(@cart.line_items)
  %tr.total_line
    %td{:colspan => "2"} Total
    %td.total_cell= number_to_currency(@cart.total_price)
= button_to 'Empty cart', @cart, :method => :delete, |
  :confirm => 'Are you sure?'                        |

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Pragprog Books Online Store
    = stylesheet_link_tag "scaffold"
    = stylesheet_link_tag "depot", :media => "all"
    = javascript_include_tag :defaults
    = csrf_meta_tag
  %body#store
    #banner
      = image_tag("ruby.jpg", :id => "logo")
      = @page_title || "Pragmatic Bookshelf"
    #columns
      #side
        %p
          =@time
        %a
          = link_to "Home", store_path
        %br/
        %a
          = link_to "Products", products_path
        %br/
        %a
          = link_to "Carts", carts_path
        %br/

      #main
        = yield

app/views/line_items/_form.html.haml
= form_for @line_item do |f|
  - if @line_item.errors.any?
    #error_explanation
      %h2= "#{pluralize(@line_item.errors.count, "error")} prohibited this line_item from being saved:"
      %ul
        - @line_item.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :product_id
    = f.number_field :product_id
  .field
    = f.label :cart_id
    = f.number_field :cart_id
  .actions
    = f.submit 'Save'

app/views/line_items/_line_item.html.haml
%tr
  %td
    = line_item.quantity
    \&times;
  %td= line_item.product.title
  %td.item_price= number_to_currency(line_item.total_price)

app/views/line_items/edit.html.haml
%h1 Editing line_item

= render 'form'

= link_to 'Show', @line_item
\|
= link_to 'Back', line_items_path

app/views/line_items/index.html.haml
%h1 Listing line_items

%table
  %thead
    %tr
      %th Product
      %th Cart
      %th
      %th
      %th
      
  %tbody
    - @line_items.each do |line_item|
      %tr
        %td= line_item.product_id
        %td= line_item.cart_id
        %td= link_to 'Show', line_item
        %td= link_to 'Edit', edit_line_item_path(line_item)
        %td= link_to 'Destroy', line_item, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Line item', new_line_item_path

app/views/line_items/new.html.haml
%h1 New line_item

= render 'form'

= link_to 'Back', line_items_path

app/views/line_items/show.html.haml
%p#notice= notice

%p
  %b Product:
  = @line_item.product_id
%p
  %b Cart:
  = @line_item.cart_id

= link_to 'Edit', edit_line_item_path(@line_item)
\|
= link_to 'Back', line_items_path

app/views/products/_form.html.haml
= form_for @product do |f|
  - if @product.errors.any?
    #error_explanation
      %h2= "#{pluralize(@product.errors.count, "error")} prohibited this product from being saved:"
      %ul
        - @product.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :description
    = f.text_area :description, :rows => 6
  .field
    = f.label :image_url
    = f.text_field :image_url
  .field
    = f.label :price
    = f.text_field :price
  .actions
    = f.submit 'Save'

app/views/products/edit.html.haml
%h1 Editing product

= render 'form'

= link_to 'Show', @product
\|
= link_to 'Back', products_path

app/views/products/index.html.haml
#product_list
  %h1 Listing products
  %table
    - @products.each do |product|
      %tr{:class => cycle('list_line_odd', 'list_line_even')}
        %td
          = image_tag(product.image_url, :class => 'list_image')
        %td.list_description
          %dl
            %dt= product.title
            %dd= truncate(strip_tags(product.description),
            :length => 80)
        %td.list_actions
          = link_to 'Show', product
          %br/
          = link_to 'Edit', edit_product_path(product)
          %br/
          = link_to 'Destroy', product,
            :confirm => 'Are you sure?',
            :method => :delete
%br/
= link_to 'New product', new_product_path

app/views/products/new.html.haml
%h1 New product

= render 'form'

= link_to 'Back', products_path

app/views/products/show.html.haml
%p#notice= notice

%p
  %b Title:
  = @product.title
%p
  %b Description:
  = @product.description
%p
  %b Image url:
  = @product.image_url
%p
  %b Price:
  = @product.price

= link_to 'Edit', edit_product_path(@product)
\|
= link_to 'Back', products_path

app/views/store/index.html.haml
- if notice
  %p#notice= notice
%h1 Your Pragmatic Catalog

- @products.each do |product|
  .entry
    = image_tag(product.image_url)
    %h3= product.title
    = sanitize(product.description)
    .price_line
      %span.price= number_to_currency(product.price)
      = button_to 'Add to Cart', line_items_path(:product_id => product)